baseurl = "https://emptysqua.re/blog/"
title = "A. Jesse Jiryu Davis"
languageCode = "en-us"
theme = "hugo_theme_emptysquare"
canonifyurls = true
copyright = "(c) A. Jesse Jiryu Davis, all rights reserved."
buildDrafts = true
footnoteReturnLinkContents = "↩"
rssLimit = 100

[params]
twitterhandle = "jessejiryudavis"
[params.author]
  name  = "A. Jesse Jiryu Davis"
  email = "jesse@emptysquare.net"

[taxonomies]
tag = "tag"
category = "category"
series = "series"

[menu]

[[menu.Main]]
    name = "All Articles"
    weight = 1
    identifier = "all-posts"
    url = "/all-posts/"

[[menu.Main]]
    name = "Feed"
    weight = 2
    identifier = "feed"
    url = "/index.xml"

[[menu.Main]]
    name = "About"
    weight = 3
    identifier = "about"
    url = "/about/"

[[menu.Main]]
    name = "Photography"
    weight = 4
    identifier = "photography"
    url = "https://portfolio.emptysqua.re/rock-climbing"

[markup]
  [markup.tableOfContents]
    endLevel = 99
    ordered = false
    startLevel = 1
  [markup.highlight]
    style = "tango"
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$']]
          inline = [['\(', '\)']]
