baseurl = "https://emptysqua.re/blog/"
title = "A. Jesse Jiryu Davis"
languageCode = "en-us"
theme = "hugo_theme_emptysquare"
canonifyurls = true
Pagination = 10
copyright = "(c) A. Jesse Jiryu Davis, all rights reserved."
disqusShortname = "emptysquare"
buildDrafts = true
footnoteReturnLinkContents = "↩"

[markup]
  [markup.tableOfContents]
    endLevel = 99
    ordered = false
    startLevel = 1

[params]
twitterhandle = "jessejiryudavis"
author = "A. Jesse Jiryu Davis"

[taxonomies]
tag = "tag"
category = "category"
series = "series"

[menu]

[[menu.Main]]
    name = "All Articles"
    weight = 1
    identifier = "all-posts"
    url = "/all-posts/"

[[menu.Main]]
    name = "Search"
    weight = 2
    identifier = "search"
    url = "/search/"

[[menu.Main]]
    name = "Feed"
    weight = 3
    identifier = "feed"
    url = "/index.xml"

[[menu.Main]]
    name = "About"
    weight = 4
    identifier = "about"
    url = "/about/"

[[menu.Main]]
    name = "Portfolio"
    weight = 5
    identifier = "portfolio"
    url = "http://portfolio.emptysqua.re/transitional-housing"

[markup.highlight]
style = "tango"
tabWidth = 4

[markup.goldmark.renderer]
unsafe = true
