baseurl = "https://emptysqua.re/blog/"
title = "A. Jesse Jiryu Davis"
languageCode = "en-us"
theme = "hugo_theme_emptysquare"
canonifyurls = true
Pagination = 10
copyright = "(c) A. Jesse Jiryu Davis, all rights reserved."
disqusShortname = "emptysquare"
pygmentsUseClassic=true
pygmentsStyle = "default"
pygmentsCodeFences = "true"
buildDrafts = true
footnoteReturnLinkContents = "↩"

[params]
twitterhandle = "jessejiryudavis"
author = "A. Jesse Jiryu Davis"

[taxonomies]
tag = "tag"
category = "category"
series = "series"

[menu]

[[menu.Main]]
    name = "All Articles"
    weight = 1
    identifier = "all-posts"
    url = "/all-posts/"

[[menu.Main]]
    name = "Feed"
    weight = 2
    identifier = "feed"
    url = "/index.xml"

[[menu.Main]]
    name = "About"
    weight = 3
    identifier = "about"
    url = "/about/"

[[menu.Main]]
    name = "Portfolio"
    weight = 4
    identifier = "portfolio"
    url = "http://portfolio.emptysqua.re/transitional-housing"
