"""Convert Excalidraw-exported SVG files back to Excalidraw JSON format.

These SVG files were exported from excalidraw.com without the "Embed scene"
option, and saved with .excalidraw extension. This script parses the SVG
elements and reconstructs Excalidraw JSON scenes.

The reconstructed scenes preserve positions, sizes, text content, and colors,
but the hand-drawn paths will be re-generated by Excalidraw (with different
random seeds), so the sketchy strokes will look slightly different.
"""

import json
import math
import random
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

SVG_NS = "http://www.w3.org/2000/svg"


def parse_transform(transform_str):
    """Extract translate(x, y) and rotate(angle, cx, cy) from transform."""
    tx, ty = 0, 0
    angle = 0
    cx, cy = 0, 0

    t_match = re.search(r"translate\(([^)]+)\)", transform_str)
    if t_match:
        parts = t_match.group(1).split()
        tx = float(parts[0])
        ty = float(parts[1]) if len(parts) > 1 else 0

    r_match = re.search(r"rotate\(([^)]+)\)", transform_str)
    if r_match:
        parts = r_match.group(1).split()
        angle = float(parts[0])
        cx = float(parts[1]) if len(parts) > 1 else 0
        cy = float(parts[2]) if len(parts) > 2 else 0

    return tx, ty, angle, cx, cy


def make_id():
    chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"
    return "".join(random.choice(chars) for _ in range(21))


def base_element(etype, x, y, w, h, stroke="#1e1e1e", stroke_width=2, angle=0):
    return {
        "id": make_id(),
        "type": etype,
        "x": x,
        "y": y,
        "width": w,
        "height": h,
        "angle": math.radians(angle),
        "strokeColor": stroke,
        "backgroundColor": "transparent",
        "fillStyle": "solid",
        "strokeWidth": stroke_width,
        "strokeStyle": "solid",
        "roughness": 1,
        "opacity": 100,
        "seed": random.randint(1, 2**31),
        "version": 1,
        "versionNonce": random.randint(1, 2**31),
        "updated": 1,
        "isDeleted": False,
        "groupIds": [],
        "frameId": None,
        "index": None,
        "roundness": {"type": 2},
        "boundElements": None,
        "link": None,
        "locked": False,
    }


def classify_group(g):
    """Determine what Excalidraw element type a <g> represents."""
    children = list(g)
    child_tags = [c.tag.replace(f"{{{SVG_NS}}}", "") for c in children]

    # Text group: contains <text> elements
    if "text" in child_tags:
        return "text"

    # Arrow/line: group with nested <g> elements
    if all(t == "g" for t in child_tags) and len(children) >= 2:
        # Check if any sub-group has arrowhead-like paths (L commands = straight lines)
        has_arrowhead = False
        for sub_g in children[1:]:
            for path_el in sub_g:
                if path_el.tag.endswith("path"):
                    d = path_el.get("d", "")
                    if " L" in d:
                        has_arrowhead = True
                        break
        return "arrow" if has_arrowhead else "line-group"

    # Check for stroke-opacity="0" fill-opacity="0" → ellipse outline
    if g.get("stroke-opacity") == "0" and g.get("fill-opacity") == "0":
        return "ellipse"

    # Two path children → filled shape (fill path + outline path)
    if len(children) == 2 and all(t == "path" for t in child_tags):
        return "filled-shape"

    # Single path child → rectangle or line or small shape
    if len(children) == 1 and child_tags[0] == "path":
        transform = g.get("transform", "")
        _, _, _, cx, cy = parse_transform(transform)
        w = cx * 2
        h = cy * 2
        if w < 10 and h < 10:
            return "small-circle"
        path = children[0]
        d = path.get("d", "")
        if d.startswith("M0 0"):
            return "rectangle"
        return "ellipse"

    # Nested group with single <g> child containing a path → line segment
    if len(children) == 1 and child_tags[0] == "g":
        return "line"

    return "unknown"


def extract_path_endpoint(d):
    """Get approximate endpoint from path data for arrows/lines."""
    # Find the last coordinate pair in the path
    coords = re.findall(r"(-?[\d.]+)\s+(-?[\d.]+)", d)
    if coords:
        return float(coords[-1][0]), float(coords[-1][1])
    return 0, 0


def parse_arrow_group(g):
    """Parse an arrow group to get start point, end point, and arrowhead info."""
    children = list(g)
    # First child group is the main line
    main_g = children[0]
    transform = main_g.get("transform", "")
    tx, ty, _, cx, cy = parse_transform(transform)

    # The path in the main group gives the arrow shape
    path_el = list(main_g)[0] if len(list(main_g)) > 0 else None
    if path_el is not None:
        d = path_el.get("d", "")
        end_x, end_y = cx * 2, cy * 2
        # Parse the M command to get actual endpoint
        # The path has two M commands (rough.js style), use the second's endpoint
        m_parts = d.split(" M")
        if len(m_parts) >= 2:
            last_part = m_parts[-1]
            coords = re.findall(r"(-?[\d.]+)\s+(-?[\d.]+)", last_part)
            if coords:
                end_x, end_y = float(coords[-1][0]), float(coords[-1][1])
    else:
        end_x, end_y = cx * 2, cy * 2

    return tx, ty, end_x, end_y


def has_arrowheads(g):
    """Check if arrow group has arrowhead sub-groups."""
    children = list(g)
    return len(children) >= 3


def convert_svg_to_excalidraw(svg_path):
    tree = ET.parse(svg_path)
    root = tree.getroot()

    # Get viewBox for coordinate reference
    viewbox = root.get("viewBox", "0 0 100 100")
    vb_parts = viewbox.split()
    vb_w = float(vb_parts[2])
    vb_h = float(vb_parts[3])

    elements = []
    skip_next_mask = False

    children = list(root)
    i = 0
    while i < len(children):
        child = children[i]
        tag = child.tag.replace(f"{{{SVG_NS}}}", "")

        if tag in ("metadata", "defs", "mask"):
            i += 1
            continue

        if tag != "g":
            i += 1
            continue

        transform = child.get("transform", "")
        if not transform and len(list(child)) == 0:
            i += 1
            continue

        etype = classify_group(child)

        if etype == "text":
            tx, ty, angle, cx, cy = parse_transform(transform)
            w = cx * 2
            h = cy * 2
            text_els = [c for c in child if c.tag.endswith("text")]
            lines = [t.text or "" for t in text_els]
            text_content = "\n".join(lines)

            # Get font info from first text element
            font_size = 20
            stroke_color = "#1e1e1e"
            if text_els:
                fs = text_els[0].get("font-size", "20px")
                font_size = int(float(fs.replace("px", "")))
                stroke_color = text_els[0].get("fill", "#1e1e1e")

            el = base_element("text", tx, ty, w, h, stroke=stroke_color, angle=angle)
            el["text"] = text_content
            el["fontSize"] = font_size
            el["fontFamily"] = 1  # Virgil (hand-drawn)
            el["textAlign"] = "center"
            el["verticalAlign"] = "top"
            el["containerId"] = None
            el["originalText"] = text_content
            el["autoResize"] = True
            el["lineHeight"] = 1.25
            del el["roundness"]
            elements.append(el)

        elif etype == "ellipse":
            tx, ty, angle, cx, cy = parse_transform(transform)
            w = cx * 2
            h = cy * 2
            path_el = [c for c in child if c.tag.endswith("path")]
            stroke = path_el[0].get("stroke", "#1e1e1e") if path_el else "#1e1e1e"
            sw_str = path_el[0].get("stroke-width", "2") if path_el else "2"
            sw = int(float(sw_str))

            el = base_element("ellipse", tx, ty, w, h, stroke=stroke, stroke_width=sw, angle=angle)
            elements.append(el)

        elif etype == "rectangle":
            tx, ty, angle, cx, cy = parse_transform(transform)
            w = cx * 2
            h = cy * 2
            path_el = [c for c in child if c.tag.endswith("path")]
            stroke = path_el[0].get("stroke", "#1e1e1e") if path_el else "#1e1e1e"
            sw_str = path_el[0].get("stroke-width", "2") if path_el else "2"
            sw = int(float(sw_str))

            el = base_element("rectangle", tx, ty, w, h, stroke=stroke, stroke_width=sw, angle=angle)
            elements.append(el)

        elif etype == "small-circle":
            tx, ty, angle, cx, cy = parse_transform(transform)
            w = cx * 2
            h = cy * 2
            path_el = [c for c in child if c.tag.endswith("path")]
            stroke = path_el[0].get("stroke", "#1e1e1e") if path_el else "#1e1e1e"

            el = base_element("ellipse", tx, ty, w, h, stroke=stroke, angle=angle)
            elements.append(el)

        elif etype == "filled-shape":
            tx, ty, angle, cx, cy = parse_transform(transform)
            w = cx * 2
            h = cy * 2
            path_els = [c for c in child if c.tag.endswith("path")]
            # First path = fill, second path = outline
            fill_path = path_els[0] if len(path_els) > 0 else None
            outline_path = path_els[1] if len(path_els) > 1 else fill_path
            bg_color = fill_path.get("fill", "transparent") if fill_path is not None else "transparent"
            stroke_color = outline_path.get("stroke", "#1e1e1e") if outline_path is not None else "#1e1e1e"
            sw_str = outline_path.get("stroke-width", "2") if outline_path is not None else "2"
            sw = int(float(sw_str))
            if bg_color == "none":
                bg_color = "transparent"

            # Determine shape: check if path looks like rectangle or ellipse
            ref_path = outline_path if outline_path is not None else fill_path
            d = ref_path.get("d", "") if ref_path is not None else ""
            shape_type = "rectangle" if d.startswith("M0 0") else "ellipse"

            el = base_element(shape_type, tx, ty, w, h, stroke=stroke_color, stroke_width=sw, angle=angle)
            el["backgroundColor"] = bg_color
            if bg_color != "transparent":
                el["fillStyle"] = "solid"
            elements.append(el)

        elif etype == "arrow":
            ax, ay, end_x, end_y = parse_arrow_group(child)

            el = base_element("arrow", ax, ay, abs(end_x), abs(end_y), angle=0)
            el["points"] = [[0, 0], [end_x, end_y]]
            el["lastCommittedPoint"] = None
            el["startBinding"] = None
            el["endBinding"] = None
            el["startArrowhead"] = None
            el["endArrowhead"] = "arrow" if has_arrowheads(child) else None
            el["roundness"] = {"type": 2}
            el["elbowed"] = False

            # Get stroke color from the main line path
            sub_groups = list(child)
            if sub_groups:
                main_paths = [c for c in sub_groups[0] if c.tag.endswith("path")]
                if main_paths:
                    el["strokeColor"] = main_paths[0].get("stroke", "#1e1e1e")

            elements.append(el)

        elif etype in ("line", "line-group"):
            sub_groups = list(child)
            inner_g = sub_groups[0]
            inner_transform = inner_g.get("transform", "")
            tx, ty, angle, cx, cy = parse_transform(inner_transform)
            end_x, end_y = cx * 2, cy * 2

            el = base_element("line", tx, ty, abs(end_x), abs(end_y), angle=0)
            el["points"] = [[0, 0], [end_x, end_y]]
            el["lastCommittedPoint"] = None
            el["startBinding"] = None
            el["endBinding"] = None
            el["startArrowhead"] = None
            el["endArrowhead"] = None
            el["roundness"] = {"type": 2}

            # Get stroke color
            inner_paths = [c for c in inner_g if c.tag.endswith("path")]
            if inner_paths:
                el["strokeColor"] = inner_paths[0].get("stroke", "#1e1e1e")

            elements.append(el)

        i += 1

    # Build the Excalidraw JSON
    scene = {
        "type": "excalidraw",
        "version": 2,
        "source": "https://excalidraw.com",
        "elements": elements,
        "appState": {
            "gridSize": None,
            "viewBackgroundColor": "#ffffff",
        },
        "files": {},
    }

    return scene


def main():
    svg_files = sorted(Path(".").glob("*.excalidraw"))
    svg_files = [f for f in svg_files if not f.name.endswith(".svg")]

    if not svg_files:
        print("No .excalidraw files found in current directory")
        sys.exit(1)

    output_dir = Path("converted")
    output_dir.mkdir(exist_ok=True)

    for svg_file in svg_files:
        print(f"Converting {svg_file.name}...")
        try:
            scene = convert_svg_to_excalidraw(str(svg_file))
            out_path = output_dir / svg_file.name
            with open(out_path, "w") as f:
                json.dump(scene, f, indent=2)
            n = len(scene["elements"])
            print(f"  -> {out_path} ({n} elements)")
        except Exception as e:
            print(f"  ERROR: {e}")


if __name__ == "__main__":
    main()
